CREATE TABLE EGOVWEB.BOARD (
	IDX NUMBER NOT NULL,
	TITLE VARCHAR(200 BYTE) NOT NULL,
	CONTENT VARCHAR(4000 BYTE) NOT NULL,
	REG_ID VARCHAR(100 BYTE),
	REG_DATE DATE,
	UPD_ID VARCHAR(100 BYTE),
	UPD_DATE DATE,
	CONSTRAINT PK_BOARD PRIMARY KEY(IDX)
);

COMMENT ON TABLE EGOVWEB.BOARD IS '게시물';

COMMENT ON COLUMN EGOVWEB.BOARD.IDX IS '게시물고유번호';

COMMENT ON COLUMN EGOVWEB.BOARD.TITLE IS '제목';

COMMENT ON COLUMN EGOVWEB.BOARD.CONTENT IS '내용';

COMMENT ON COLUMN EGOVWEB.BOARD.REG_ID IS '등록자';

COMMENT ON COLUMN EGOVWEB.BOARD.REG_DATE IS '등록일';

COMMENT ON COLUMN EGOVWEB.BOARD.UPD_ID IS '수정자';

COMMENT ON COLUMN EGOVWEB.BOARD.UPD_DATE IS '수정일';
